import { Business, Deal, Review, User, SpoteraStory } from '../types';

export const defaultGuestUser: User = {
  id: '',
  name: 'Guest User',
  email: '',
  phone: '',
  username: 'guest',
  avatar: '',
  gender: 'Family',
  age: 32,
  location: 'Dubai',
  role: 'customer',
  membership: 'Free',
  savedDealIds: [],
  notifications: [],
  walletBalanceAED: 50,
  walletEarnedTotalAED: 50,
  walletUsedTotalAED: 0,
  walletTransactions: [
    {
      id: 'tx_1',
      type: 'referral_credit',
      amountAED: 25,
      description: 'Spotera Welcome Bonus Credit',
      date: '2026-08-01',
      status: 'completed',
    },
    {
      id: 'tx_2',
      type: 'referral_credit',
      amountAED: 25,
      description: 'Family Invite Reward Credit',
      date: '2026-08-05',
      status: 'completed',
    },
  ],
};

export const initialUser: User = defaultGuestUser;

export const initialBusinesses: Business[] = [
  {
    id: 'biz_kidzania_dubai',
    name: 'KidZania Dubai Mall',
    category: 'Kids Play Areas',
    city: 'Dubai',
    district: 'Downtown Dubai',
    address: 'Level 2, Dubai Mall, Downtown Dubai, UAE',
    coordinates: { lat: 25.1972, lng: 55.2744 },
    description: 'An interactive mini-city combining play with learning! Over 80 role-play activities for kids where they can become firemen, doctors, chefs, pilots, and radio hosts.',
    images: [
      'https://images.unsplash.com/photo-1566454544259-f4b94c96a464?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&q=80&w=1000',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    openingHours: 'Mon - Sun: 10:00 AM - 10:00 PM',
    phone: '+971 4 448 5222',
    email: 'info@kidzania.ae',
    rating: 4.9,
    reviewCount: 620,
    status: 'approved',
    verified: true,
    isFeatured: true,
    isSpoteraExclusive: true,
  },
  {
    id: 'biz_olioli_dubai',
    name: "OliOli Children's Experiential Museum",
    category: 'Kids Play Areas',
    city: 'Dubai',
    district: 'Al Quoz 1',
    address: '12 4B Street, Al Quoz 1, Dubai, UAE',
    coordinates: { lat: 25.1382, lng: 55.2312 },
    description: 'Award-winning experiential play museum with 8 themed galleries and over 45 interactive hands-on exhibits including Toshi’s Net, Water Gallery, and Future Park.',
    images: [
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=1000',
    ],
    openingHours: 'Mon - Sun: 9:00 AM - 7:00 PM',
    phone: '+971 4 702 7300',
    email: 'hello@olioli.ae',
    rating: 4.9,
    reviewCount: 480,
    status: 'approved',
    verified: true,
    isFeatured: true,
    isSpoteraExclusive: true,
  },
  {
    id: 'biz_wild_wadi',
    name: 'Wild Wadi Waterpark',
    category: 'Attractions',
    city: 'Dubai',
    district: 'Jumeirah',
    address: 'Jumeirah Street, Next to Burj Al Arab, Dubai, UAE',
    coordinates: { lat: 25.1412, lng: 55.1901 },
    description: 'Dubai’s iconic aquatic theme park situated in front of Burj Al Arab with 30 water rides, wave pool, lazy river, and toddler splash play area Juha’s Dhow & Lagoon.',
    images: [
      'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000',
    ],
    openingHours: 'Mon - Sun: 10:00 AM - 6:00 PM',
    phone: '+971 4 348 4444',
    email: 'wwinfo@jumeirah.com',
    rating: 4.8,
    reviewCount: 890,
    status: 'approved',
    verified: true,
    isFeatured: true,
    isSpoteraExclusive: true,
  },
  {
    id: 'biz_air_maniax',
    name: 'Air Maniax Adventure & Inflatable Park',
    category: 'Entertainment',
    city: 'Dubai',
    district: 'Al Quoz 1',
    address: 'Street 16, Al Quoz 1, Dubai, UAE',
    coordinates: { lat: 25.1321, lng: 55.2289 },
    description: '15,000 sq ft inflatable indoor arena featuring Zip Line, Warrior Assault Course, Lazer Frenzy, Toddler Zone, and inflatable obstacle slides.',
    images: [
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&q=80&w=1000',
    ],
    openingHours: 'Mon - Sun: 9:00 AM - 9:00 PM',
    phone: '+971 4 348 8981',
    email: 'info@airmaniax.com',
    rating: 4.7,
    reviewCount: 340,
    status: 'approved',
    verified: true,
    isFeatured: true,
  },
  {
    id: 'biz_yas_waterworld',
    name: 'Yas Waterworld Abu Dhabi',
    category: 'Attractions',
    city: 'Abu Dhabi',
    district: 'Yas Island',
    address: 'Yas Island, Abu Dhabi, UAE',
    coordinates: { lat: 24.4891, lng: 54.6082 },
    description: 'Emirati-themed waterpark with over 45 rides, slides, and attractions, including Falcon’s Falaj hydro-magnetic coaster and Marah Fortress for toddlers.',
    images: [
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1000',
    ],
    openingHours: 'Mon - Sun: 10:00 AM - 7:00 PM',
    phone: '+971 600 511115',
    email: 'contact@yaswaterworld.com',
    rating: 4.9,
    reviewCount: 750,
    status: 'approved',
    verified: true,
    isFeatured: true,
    isSpoteraExclusive: true,
  },
  {
    id: 'biz_orange_wheels',
    name: 'Orange Wheels Playland',
    category: 'Kids Play Areas',
    city: 'Abu Dhabi',
    district: 'Al Wahda Mall',
    address: 'Al Wahda Mall 3rd Floor, Abu Dhabi, UAE',
    coordinates: { lat: 24.4712, lng: 54.3721 },
    description: 'Educational & fun indoor play concept offering gym climbing walls, arts and craft studio, salon, pretend play town, and organic cafe.',
    images: [
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?auto=format&fit=crop&q=80&w=1000',
    ],
    openingHours: 'Mon - Sun: 10:00 AM - 10:00 PM',
    phone: '+971 2 556 2229',
    email: 'hello@orangewheels.com',
    rating: 4.8,
    reviewCount: 310,
    status: 'approved',
    verified: true,
    isFeatured: true,
  },
  {
    id: 'biz_ski_dubai',
    name: 'Ski Dubai Snow Park',
    category: 'Attractions',
    city: 'Dubai',
    district: 'Mall of the Emirates',
    address: 'Mall of the Emirates, Al Barsha 1, Dubai, UAE',
    coordinates: { lat: 25.1181, lng: 55.2006 },
    description: 'Middle East’s first indoor ski resort with real snow year-round! Features Snow Park, bobsled runs, tobogganing hills, and real penguin encounters.',
    images: [
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1000',
    ],
    openingHours: 'Mon - Sun: 10:00 AM - 11:00 PM',
    phone: '+971 4 409 4000',
    email: 'info@skidxb.com',
    rating: 4.9,
    reviewCount: 920,
    status: 'approved',
    verified: true,
    isFeatured: true,
    isSpoteraExclusive: true,
  },
  {
    id: 'biz_green_planet',
    name: 'The Green Planet Dubai',
    category: 'Family Experiences',
    city: 'Dubai',
    district: 'City Walk',
    address: 'City Walk, Al Wasl, Dubai, UAE',
    coordinates: { lat: 25.2062, lng: 55.2621 },
    description: 'Enclosed indoor bio-dome simulating a tropical rainforest with over 3,000 plants and animals, sloth encounters, toucans, and rain showers.',
    images: [
      'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&q=80&w=1000',
    ],
    openingHours: 'Mon - Sun: 10:00 AM - 6:00 PM',
    phone: '+971 800 7699',
    email: 'info@thegreenplanetdubai.ae',
    rating: 4.8,
    reviewCount: 510,
    status: 'approved',
    verified: true,
    isFeatured: true,
  },
];

export const initialDeals: Deal[] = [
  {
    id: 'deal_little_world',
    businessId: 'biz_little_world',
    businessName: 'Little World Play Area',
    title: 'Little World Play Area — Dubai Marina',
    description: 'Immersive soft play, sensory zones, discovery rooms, and giant ball pit designed for children and toddlers.',
    category: 'Kids Play Areas',
    city: 'Dubai',
    district: 'Dubai Marina',
    location: 'Dubai Marina Walk',
    originalPrice: 89,
    discountPrice: 54,
    discountPercent: 40,
    images: [
      'https://images.unsplash.com/photo-1511882150382-421056c89033?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1566454544259-f4b94c96a464?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Grip socks required', 'Adults enter free with child'],
    expiryDate: '2026-12-31',
    rating: 4.8,
    reviewCount: 320,
    isFeatured: true,
    isTrending: true,
    isIndoor: true,
    targetAgeGroup: 'Ages 1–8',
    openingHours: 'Open daily 09:30 – 21:00',
    whatIsIncluded: [
      'Full 2-hour sensory play access',
      'Giant interactive ball pool & tube slides',
      'Free entry for 1 parent/guardian',
    ],
    whatToBring: ['Grip socks'],
    importantInfo: 'Sanitized every hour. Clean socks mandatory.',
    packages: [
      { id: 'pkg_lw_1', name: '2-Hour Play Pass', price: 54, description: '1 child + 1 adult entry', duration: '2 Hours' },
    ],
    availability: 'available',
  },
  {
    id: 'deal_aquaplay',
    businessId: 'biz_aquaplay',
    businessName: 'AquaPlay Waterpark',
    title: 'AquaPlay Waterpark — 2 Kids Entry',
    description: 'Dubai’s most exciting indoor aquatic adventure park with family splash slides, lazy river pools, bumper boats, and water spray towers.',
    category: 'Family Experiences',
    city: 'Dubai',
    district: 'Dubai Marina',
    location: 'Dubai Marina Walk — 2.3 km away',
    originalPrice: 160,
    discountPrice: 99,
    discountPercent: 38,
    images: [
      'https://images.unsplash.com/photo-1566454544259-f4b94c96a464?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Valid 7 days a week', 'Towel and lockers included', 'Free entry for 2 accompanying adults'],
    expiryDate: '2026-12-31',
    rating: 4.8,
    reviewCount: 412,
    isFeatured: true,
    isTrending: true,
    isIndoor: true,
    targetAgeGroup: 'Ages 3–12 · Adults must accompany',
    openingHours: 'Open daily 10:00 – 19:00',
    whatIsIncluded: [
      'Full-day access for 2 children',
      'Towels and lockers included',
      'Kids’ splash zone and slides',
      'Free entry for 2 accompanying adults',
    ],
    whatToBring: ['Swimwear', 'Waterproof pouch'],
    importantInfo: 'Lockers and showers provided on site.',
    packages: [
      { id: 'pkg_ap_1', name: '2 Kids Entry (Full Day)', price: 99, description: 'Full access for 2 kids + 2 adults free', duration: 'Full Day' },
      { id: 'pkg_ap_2', name: 'Family Mega Splash Pass', price: 179, description: '4 kids + lockers + lunch vouchers', duration: 'Full Day' },
    ],
    availability: 'available',
  },
  {
    id: 'deal_family_brunch',
    businessId: 'biz_jbr_brunch',
    businessName: 'The Shoreline Grill & Terrace',
    title: 'Family Brunch — JBR',
    description: 'Relaxing weekend seaside family brunch with international live cooking stations, dedicated kids buffet, and outdoor playground.',
    category: 'Restaurants',
    city: 'Dubai',
    district: 'JBR',
    location: 'The Walk, JBR — 1.8 km away',
    originalPrice: 280,
    discountPrice: 199,
    discountPercent: 29,
    images: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Children under 5 dine free', 'Advance reservation advised'],
    expiryDate: '2026-12-31',
    rating: 4.7,
    reviewCount: 185,
    isFeatured: true,
    targetAgeGroup: 'All Ages',
    openingHours: 'Fridays & Saturdays: 12:30 – 16:30',
    whatIsIncluded: ['Full international buffet with seafood and carving stations', 'Kids entertainment area', 'Free valet parking'],
    whatToBring: ['Smart casual attire'],
    packages: [
      { id: 'pkg_brunch_1', name: 'Family Buffet Brunch', price: 199, description: 'Adult brunch pass + kids buffet access', duration: '4 Hours' },
    ],
    availability: 'limited',
  },
  {
    id: 'deal_kidz_climbing',
    businessId: 'biz_kidz_climbing',
    businessName: 'KidZ Climbing Academy',
    title: 'KidZ Climbing — Al Quoz',
    description: 'Safe indoor bouldering and harness rock climbing with qualified instructors and 25 themed climbing walls.',
    category: 'Entertainment',
    city: 'Dubai',
    district: 'Al Quoz',
    location: 'Al Quoz Industrial 1 — 3.1 km away',
    originalPrice: 75,
    discountPrice: 45,
    discountPercent: 40,
    images: [
      'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Harness and climbing shoes provided', 'Weight limit 15kg - 110kg'],
    expiryDate: '2026-12-31',
    rating: 4.6,
    reviewCount: 128,
    isFeatured: true,
    targetAgeGroup: 'Ages 4+',
    openingHours: 'Open daily 10:00 – 21:00',
    whatIsIncluded: ['60 minutes harness climbing', 'Safety briefing and gear rental', 'Instructor guidance'],
    whatToBring: ['Sports shoes and athletic wear'],
    packages: [
      { id: 'pkg_climb_1', name: '60-Min Climbing Session', price: 45, description: 'Includes harness, gear & briefing', duration: '1 Hour' },
    ],
    availability: 'available',
  },
  {
    id: 'deal_kidzania_1',
    businessId: 'biz_kidzania_dubai',
    businessName: 'KidZania Dubai Mall',
    title: 'All-Day Junior Pass + KidZos Bonus Currency Pack',
    description: 'Full day unlimited access to KidZania role-play city. Includes 50 KidZos bonus currency for kids to spend in bank, bakery, or driving school.',
    category: 'Kids Play Areas',
    city: 'Dubai',
    district: 'Downtown Dubai',
    originalPrice: 220,
    discountPrice: 145,
    discountPercent: 34,
    images: [
      'https://images.unsplash.com/photo-1566454544259-f4b94c96a464?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: [
      'Valid 7 days a week at Dubai Mall',
      'Adults must be accompanied by at least 1 child',
      'Free entry for infants under 2 years old',
    ],
    expiryDate: '2026-12-31',
    rating: 4.9,
    reviewCount: 310,
    isFeatured: true,
    isSpoteraExclusive: true,
    isIndoor: true,
    targetAgeGroup: '2 - 16 Years',
    openingHours: 'Mon - Sun: 10:00 AM - 10:00 PM',
    whatIsIncluded: [
      'All day entry to KidZania Dubai',
      '50 KidZos bonus play currency',
      'Access to 80+ roleplay occupations',
    ],
    whatToBring: ['Comfortable shoes', 'Socks'],
    importantInfo: 'Re-entry permitted with wristband.',
    packages: [
      { id: 'pkg_kz_1', name: 'Single Child All-Day Pass', price: 145, description: '1 Child entry + 50 KidZos', duration: 'Full Day' },
      { id: 'pkg_kz_2', name: 'Family Combo (2 Kids + 2 Adults)', price: 420, description: '2 Kids + 2 Adults full access', duration: 'Full Day' },
    ],
  },
  {
    id: 'deal_olioli_1',
    businessId: 'biz_olioli_dubai',
    businessName: 'OliOli Play Museum',
    title: '2-Hour Experiential Play Pass (1 Child + 1 Adult Free)',
    description: 'Explore 8 hands-on galleries including Toshi’s Net, Water Gallery, and Launch Pad. 1 accompanying adult enters free with every child ticket!',
    category: 'Kids Play Areas',
    city: 'Dubai',
    district: 'Al Quoz 1',
    originalPrice: 180,
    discountPrice: 120,
    discountPercent: 33,
    images: [
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Grip socks required for Toshi’s Net gallery', 'Advance online time slot reservation recommended'],
    expiryDate: '2026-11-30',
    rating: 4.9,
    reviewCount: 280,
    isFeatured: true,
    isSpoteraExclusive: true,
    isIndoor: true,
    targetAgeGroup: '1 - 11 Years',
    openingHours: 'Mon - Sun: 9:00 AM - 7:00 PM',
    whatIsIncluded: ['2 hours entry to all 8 galleries', '1 Free accompanying adult ticket', 'Access to waterplay lab'],
    whatToBring: ['Extra change of clothes for water gallery', 'Socks'],
    importantInfo: 'Sanitized constantly after every session.',
    packages: [
      { id: 'pkg_oli_1', name: 'Child + Adult Pass (2 Hours)', price: 120, description: '2 hours access for 1 child + 1 adult', duration: '2 Hours' },
    ],
  },
  {
    id: 'deal_ski_dubai_1',
    businessId: 'biz_ski_dubai',
    businessName: 'Ski Dubai Snow Park',
    title: 'Unlimited Snow Park Pass + Hot Chocolate Voucher',
    description: 'Chill out in real snow! Enjoy unlimited rides on the Snow Bullet, Tobogganing, Bobsled, Giant Snowball, and a complimentary signature hot chocolate.',
    category: 'Attractions',
    city: 'Dubai',
    district: 'Mall of the Emirates',
    originalPrice: 295,
    discountPrice: 195,
    discountPercent: 34,
    images: [
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Winter jackets, snow pants, socks & boots provided', 'Fleece gloves included to take home'],
    expiryDate: '2026-12-31',
    rating: 4.9,
    reviewCount: 460,
    isFeatured: true,
    isSpoteraExclusive: true,
    isIndoor: true,
    targetAgeGroup: '2 - 16 Years',
    openingHours: 'Mon - Sun: 10:00 AM - 11:00 PM',
    whatIsIncluded: ['Full day Snow Park ride access', 'Winter clothing rental', 'Fleece gloves', 'Hot Chocolate voucher'],
    whatToBring: ['Warm beanie hat'],
    importantInfo: 'Locker rental included for full day.',
    packages: [
      { id: 'pkg_ski_1', name: 'Snow Park Classic Pass', price: 195, description: 'Snow park rides + gear + hot chocolate', duration: 'Full Day' },
    ],
  },
  {
    id: 'deal_green_planet_1',
    businessId: 'biz_green_planet',
    businessName: 'The Green Planet Dubai',
    title: 'Rainforest Bio-Dome Pass + Creature Encounter',
    description: 'Walk through 4 stories of tropical flora and fauna. Get up close with sloths, sugar gliders, piranhas, and colorful toucans in Dubai’s indoor rainforest.',
    category: 'Family Experiences',
    city: 'Dubai',
    district: 'City Walk',
    originalPrice: 160,
    discountPrice: 110,
    discountPercent: 31,
    images: [
      'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Valid 7 days a week', 'Free admission for infants under 2 years old'],
    expiryDate: '2026-11-30',
    rating: 4.8,
    reviewCount: 340,
    isFeatured: true,
    isSpoteraExclusive: false,
    isIndoor: true,
    targetAgeGroup: 'All Ages',
    openingHours: 'Mon - Sun: 10:00 AM - 6:00 PM',
    whatIsIncluded: ['Bio-Dome entrance', 'Access to tropical bird feed session', 'Piranha feeding talk'],
    whatToBring: ['Camera (no flash)'],
    importantInfo: 'Stroller accessible throughout all 4 floors.',
    packages: [
      { id: 'pkg_gp_1', name: 'Bio-Dome General Pass', price: 110, description: 'Full access to rainforest floors & talks', duration: '2 Hours' },
    ],
  },
  {
    id: 'deal_wild_wadi_1',
    businessId: 'biz_wild_wadi',
    businessName: 'Wild Wadi Waterpark',
    title: 'Day Access Pass + Meal Voucher Combo',
    description: 'Splash through 30 water rides including Jumeirah Sceirah and Wipeout Flowrider. Comes with a complimentary lunch burger & drink voucher!',
    category: 'Attractions',
    city: 'Dubai',
    district: 'Jumeirah',
    originalPrice: 330,
    discountPrice: 210,
    discountPercent: 36,
    images: [
      'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Valid for heights 1.1m and above', 'Includes AED 40 lunch voucher at Surfer’s Burgers'],
    expiryDate: '2026-12-15',
    rating: 4.8,
    reviewCount: 520,
    isFeatured: true,
    isSpoteraExclusive: true,
    isOutdoor: true,
    targetAgeGroup: 'All Ages',
    openingHours: 'Mon - Sun: 10:00 AM - 6:00 PM',
    whatIsIncluded: ['Unlimited ride pass', 'Lunch burger meal & drink voucher', 'Life jacket rental'],
    whatToBring: ['Swimwear', 'Sunscreen', 'Towel'],
    importantInfo: 'Lockers available on site for hire.',
    packages: [
      { id: 'pkg_ww_1', name: 'General Admission + Meal', price: 210, description: 'Full day waterpark admission + meal voucher', duration: 'Full Day' },
    ],
  },
  {
    id: 'deal_air_maniax_1',
    businessId: 'biz_air_maniax',
    businessName: 'Air Maniax Adventure',
    title: '1-Hour Inflatable Arena & Zip Line Unlimited Pass',
    description: 'Jump, climb, and zip-line through 15,000 sq ft of inflatable obstacle courses, laser tag, and ninja warrior arenas.',
    category: 'Entertainment',
    city: 'Dubai',
    district: 'Al Quoz 1',
    originalPrice: 120,
    discountPrice: 75,
    discountPercent: 37,
    images: [
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Air Maniax grip socks required (AED 10 at counter if needed)', 'Height limit 95cm+ for main arena'],
    expiryDate: '2026-10-31',
    rating: 4.7,
    reviewCount: 190,
    isFeatured: false,
    isIndoor: true,
    targetAgeGroup: '3 - 16 Years',
    openingHours: 'Mon - Sun: 9:00 AM - 9:00 PM',
    whatIsIncluded: ['1 hour inflatable arena access', 'Unlimited zip line rides', 'Ninja course timed challenge'],
    whatToBring: ['Grip socks'],
    importantInfo: 'Dedicated toddler zone for under 95cm.',
    packages: [
      { id: 'pkg_am_1', name: '1-Hour General Jump Pass', price: 75, description: '1 Hour full arena jump access', duration: '1 Hour' },
    ],
  },
  {
    id: 'deal_yas_waterworld_1',
    businessId: 'biz_yas_waterworld',
    businessName: 'Yas Waterworld Abu Dhabi',
    title: 'Single Day Admission Ticket with Quick Pass Upgrade',
    description: 'Experience UAE’s premier Emirati water kingdom on Yas Island with fast track access to 10 top rides!',
    category: 'Attractions',
    city: 'Abu Dhabi',
    district: 'Yas Island',
    originalPrice: 325,
    discountPrice: 215,
    discountPercent: 34,
    images: [
      'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: ['Free shuttle service from Dubai Mall & Mall of the Emirates available', 'Valid 7 days a week'],
    expiryDate: '2026-12-31',
    rating: 4.9,
    reviewCount: 390,
    isFeatured: true,
    isSpoteraExclusive: true,
    isOutdoor: true,
    targetAgeGroup: 'All Ages',
    openingHours: 'Mon - Sun: 10:00 AM - 7:00 PM',
    whatIsIncluded: ['Full day admission', 'Quick Pass queue skip for top 10 rides', 'Free park shuttle bus from Dubai'],
    whatToBring: ['Swimwear', 'Towels'],
    importantInfo: 'Free entry for children under 3.',
    packages: [
      { id: 'pkg_yw_1', name: 'Yas Day Ticket + Quick Pass', price: 215, description: '1 Day admission with priority queue pass', duration: 'Full Day' },
    ],
  },
  {
    id: 'deal_orange_wheels_birthday',
    businessId: 'biz_orange_wheels',
    businessName: 'Orange Wheels Playland',
    title: 'All-Inclusive Kids Birthday Party Package for 10 Children',
    description: 'Celebration time! Private decorated party room, 2 hours soft playland access, customized theme birthday cake, kids pizza meals, balloons, and host animator.',
    category: 'Birthday Parties',
    city: 'Abu Dhabi',
    district: 'Al Wahda Mall',
    originalPrice: 1850,
    discountPrice: 1290,
    discountPercent: 30,
    images: [
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?auto=format&fit=crop&q=80&w=1000',
    ],
    terms: [
      'Advance reservation at least 48 hours in advance',
      'Includes up to 10 children (extra kids AED 95 per child)',
      'Custom theme room decorations included',
    ],
    expiryDate: '2026-12-31',
    rating: 4.9,
    reviewCount: 140,
    isFeatured: true,
    isSpoteraExclusive: true,
    isIndoor: true,
    targetAgeGroup: '1 - 10 Years',
    openingHours: 'Mon - Sun: 10:00 AM - 10:00 PM',
    whatIsIncluded: ['2 hours soft play access for 10 kids', 'Private theme decorated room', '2kg customized birthday cake', 'Individual kids pizza meal + juice box', 'Party host animator'],
    whatToBring: ['Birthday candles & camera!'],
    importantInfo: 'Sound system & music player provided in party room.',
    packages: [
      { id: 'pkg_bd_1', name: 'Silver Birthday Package (10 Kids)', price: 1290, description: 'Play + Decorated Room + Cake + Meals', duration: '2.5 Hours' },
      { id: 'pkg_bd_2', name: 'Gold Birthday Package (15 Kids + Face Paint)', price: 1790, description: 'Includes 15 kids + face painting & photo booth', duration: '3 Hours' },
    ],
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev_1',
    dealId: 'deal_kidzania_1',
    userId: 'usr_2',
    userName: 'Fatima Al Mansoori',
    userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=120',
    rating: 5,
    comment: 'KidZania at Dubai Mall is fantastic! The children loved working as firemen and doctors. Saved 150 AED using our Spotera digital coupon.',
    date: '2026-08-02',
    verifiedPurchase: true,
  },
  {
    id: 'rev_2',
    dealId: 'deal_wild_wadi_1',
    userId: 'usr_3',
    userName: 'Zayed Al Hashmi',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120',
    rating: 5,
    comment: 'Wild Wadi waterpark trip with our kids was the highlight of our weekend! The burger lunch combo voucher saved us so much time and money.',
    date: '2026-08-04',
    verifiedPurchase: true,
  },
  {
    id: 'rev_3',
    dealId: 'deal_olioli_1',
    userId: 'usr_4',
    userName: 'Rashid Al Ketbi',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=120',
    rating: 5,
    comment: 'Took my 4-year-old to OliOli in Al Quoz. The water gallery and Toshi’s net are world class. Instant coupon redemption at counter.',
    date: '2026-07-28',
    verifiedPurchase: true,
  },
];

export const initialStories: SpoteraStory[] = [
  {
    id: 'story_1',
    title: 'Top 5 Indoor Cool-Down Spots for UAE Kids',
    subtitle: 'Beat the heat with air-conditioned play parks, interactive museums, and VR arenas.',
    category: 'Weekend Guide',
    image: 'https://images.unsplash.com/photo-1566454544259-f4b94c96a464?auto=format&fit=crop&q=80&w=800',
    badge: 'MUST TRY',
    readTime: '3 min read',
    dealId: 'deal_kidzania_1',
    linkText: 'Explore KidZania Deal',
  },
  {
    id: 'story_2',
    title: 'Wild Wadi & Yas Waterworld Splash Day Tips',
    subtitle: 'How to maximize your day at UAE’s top wave pools & slide kingdoms.',
    category: 'Day Trip Guide',
    image: 'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=800',
    badge: 'FAMILY FAVORITE',
    readTime: '4 min read',
    dealId: 'deal_wild_wadi_1',
    linkText: 'Get Waterpark Pass',
  },
  {
    id: 'story_3',
    title: 'Best Birthday Party Venues in Dubai & Abu Dhabi',
    subtitle: 'Plan a stress-free party with private rooms, custom cakes, and soft play fun.',
    category: 'Birthday Guide',
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&q=80&w=800',
    badge: 'PARTY TIME',
    readTime: '2 min read',
    dealId: 'deal_orange_wheels_birthday',
    linkText: 'View Birthday Deals',
  },
];

export const initialHeroSlides = [
  {
    id: 'slide-1',
    title: 'Iconic Dubai Skyline & City Attractions',
    subtitle: 'Save up to 50% on Burj Khalifa decks, Dubai Frame, luxury cruises & desert safaris.',
    badge: 'DUBAI HIGHLIGHTS • EXCLUSIVE PASSES',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1920&q=80',
    buttonText: 'Explore Dubai Deals',
    buttonLink: 'explore',
    enabled: true,
    order: 1,
  },
  {
    id: 'slide-2',
    title: 'Dubai Marina & Waterfront Dining',
    subtitle: 'Savor Michelin-star meals, family brunches & luxury yacht rentals across Dubai & Abu Dhabi.',
    badge: 'GOURMET & FAMILY DINING',
    imageUrl: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1920&q=80',
    buttonText: 'Discover Dining Offers',
    buttonLink: 'category:Restaurants',
    enabled: true,
    order: 2,
  },
  {
    id: 'slide-3',
    title: 'Palm Jumeirah & Beach Staycations',
    subtitle: 'Unwind at world-class 5-star beachfront resorts, Aquaventure waterpark & private beach clubs.',
    badge: 'RESORTS & STAYCATIONS',
    imageUrl: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?auto=format&fit=crop&w=1920&q=80',
    buttonText: 'View Staycation Deals',
    buttonLink: 'category:Hotels',
    enabled: true,
    order: 3,
  },
  {
    id: 'slide-4',
    title: 'Yas Island & Abu Dhabi Mega Parks',
    subtitle: 'Unlimited thrill passes for Ferrari World, Yas Waterworld, Warner Bros & SeaWorld Abu Dhabi.',
    badge: 'YAS ISLAND PASSES',
    imageUrl: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1920&q=80',
    buttonText: 'Get Theme Park Passes',
    buttonLink: 'category:Attractions',
    enabled: true,
    order: 4,
  },
  {
    id: 'slide-5',
    title: 'Kids Soft Play & Family Entertainment',
    subtitle: 'All-day access to top trampoline parks, indoor snow parks, VR arcades & creative workshops.',
    badge: 'KIDS & FAMILY EXPERIENCES',
    imageUrl: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=1920&q=80',
    buttonText: 'Explore Kids Passes',
    buttonLink: 'category:Kids Play Areas',
    enabled: true,
    order: 5,
  },
];

export const initialCategoriesList = [
  { id: 'cat-1', name: 'Kids Play Areas', iconName: 'Gamepad2', enabled: true, order: 1, badge: 'Popular' },
  { id: 'cat-2', name: 'Attractions', iconName: 'Sparkles', enabled: true, order: 2, badge: 'Top Rated' },
  { id: 'cat-3', name: 'Family Experiences', iconName: 'Users', enabled: true, order: 3 },
  { id: 'cat-4', name: 'Restaurants', iconName: 'Utensils', enabled: true, order: 4, badge: '2-For-1' },
  { id: 'cat-5', name: 'Hotels', iconName: 'Hotel', enabled: true, order: 5 },
  { id: 'cat-6', name: 'Entertainment', iconName: 'Film', enabled: true, order: 6 },
  { id: 'cat-7', name: 'Summer Camps', iconName: 'Compass', enabled: true, order: 7 },
  { id: 'cat-8', name: 'Birthday Parties', iconName: 'Gift', enabled: true, order: 8 },
  { id: 'cat-9', name: 'Workshops', iconName: 'BookOpen', enabled: true, order: 9 },
];

export const initialLocationsList = [
  {
    id: 'loc-dubai',
    emirate: 'Dubai' as const,
    areas: ['Downtown Dubai', 'Dubai Marina', 'Palm Jumeirah', 'Business Bay', 'JBR', 'Al Barsha', 'Deira', 'Mirdif'],
    enabled: true,
    order: 1,
  },
  {
    id: 'loc-abudhabi',
    emirate: 'Abu Dhabi' as const,
    areas: ['Yas Island', 'Saadiyat Island', 'Corniche', 'Al Maryah Island', 'Khalifa City', 'Al Reem Island'],
    enabled: true,
    order: 2,
  },
  {
    id: 'loc-sharjah',
    emirate: 'Sharjah' as const,
    areas: ['Al Majaz', 'Al Qasba', 'University City', 'Al Khan', 'Muwaileh'],
    enabled: true,
    order: 3,
  },
  {
    id: 'loc-ajman',
    emirate: 'Ajman' as const,
    areas: ['Ajman Corniche', 'Al Nuaimiya', 'Al Rashidiya'],
    enabled: true,
    order: 4,
  },
  {
    id: 'loc-rak',
    emirate: 'Ras Al Khaimah' as const,
    areas: ['Al Marjan Island', 'Jebel Jais', 'Al Hamra'],
    enabled: true,
    order: 5,
  },
  {
    id: 'loc-fujairah',
    emirate: 'Fujairah' as const,
    areas: ['Al Aqah Beach', 'Fujairah City', 'Dibba'],
    enabled: true,
    order: 6,
  },
  {
    id: 'loc-ummalquwain',
    emirate: 'Umm Al Quwain' as const,
    areas: ['Dreamland Aqua Park', 'Al Salamah'],
    enabled: true,
    order: 7,
  },
];

export const initialMediaLibrary = [
  {
    id: 'media-1',
    title: 'Dubai Skyline & Burj Khalifa',
    url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1920&q=80',
    category: 'dubai-skyline' as const,
    uploadedAt: '2026-09-01',
  },
  {
    id: 'media-2',
    title: 'Dubai Marina Luxury Waterfront',
    url: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1920&q=80',
    category: 'dubai-skyline' as const,
    uploadedAt: '2026-09-01',
  },
  {
    id: 'media-3',
    title: 'Palm Jumeirah Atlantis Scenery',
    url: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?auto=format&fit=crop&w=1920&q=80',
    category: 'hotel' as const,
    uploadedAt: '2026-09-01',
  },
  {
    id: 'media-4',
    title: 'Yas Island Abu Dhabi Adventure',
    url: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1920&q=80',
    category: 'attraction' as const,
    uploadedAt: '2026-09-01',
  },
  {
    id: 'media-5',
    title: 'Burj Al Arab Luxury Coastal View',
    url: 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&w=1920&q=80',
    category: 'dubai-skyline' as const,
    uploadedAt: '2026-09-01',
  },
  {
    id: 'media-6',
    title: 'Dubai Frame & Zabeel Park',
    url: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?auto=format&fit=crop&w=1920&q=80',
    category: 'attraction' as const,
    uploadedAt: '2026-09-01',
  },
  {
    id: 'media-7',
    title: 'Kids Indoor Trampoline & Soft Play',
    url: 'https://images.unsplash.com/photo-1566454544259-f4b94c96a464?auto=format&fit=crop&w=1920&q=80',
    category: 'kids' as const,
    uploadedAt: '2026-09-01',
  },
  {
    id: 'media-8',
    title: 'Waterpark Wave Pool Adventure',
    url: 'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&w=1920&q=80',
    category: 'attraction' as const,
    uploadedAt: '2026-09-01',
  },
];

export const initialBrandingConfig = {
  siteName: 'SpoteraDeals',
  tagline: 'UAE Family Deals & Experiences',
  primaryColor: '#0D9CFD',
  accentColor: '#FD9302',
  fontFamily: 'Outfit',
  headingFont: 'Outfit',
  bodyFont: 'Plus Jakarta Sans',
  buttonFont: 'Outfit',
  headingFontSize: '1rem',
  bodyFontSize: '0.9375rem',
  buttonFontSize: '0.875rem',
  letterSpacing: 'normal',
  heroMediaType: 'slideshow' as const,
};

export const initialUserRequests = [
  {
    id: 'req_1',
    userId: 'guest',
    userName: 'Sarah Jenkins',
    userPhone: '+971 50 123 4567',
    userEmail: 'sarah.j@example.com',
    title: '300 Fresh Mini Croissants & Pastries for Corporate Breakfast',
    category: 'Food & Beverage',
    city: 'Dubai' as const,
    district: 'Downtown Dubai',
    neededDate: 'This Friday (7:30 AM)',
    budgetAED: 1200,
    details: 'Need 150 butter croissants, 75 chocolate pains, and 75 fruit danishes packaged in catering presentation platters for morning keynote conference.',
    status: 'quote_received' as const,
    createdAt: '2026-09-04T09:15:00Z',
    quotesCount: 2,
  },
  {
    id: 'req_2',
    userId: 'guest',
    userName: 'Ahmad Al Nuaimi',
    userPhone: '+971 55 987 6543',
    userEmail: 'ahmad.nuaimi@example.com',
    title: 'AC Duct Deep Cleaning & Sanitization for 4-Bedroom Villa',
    category: 'Home & Maintenance',
    city: 'Dubai' as const,
    district: 'Arabian Ranches 2',
    neededDate: 'Saturday morning',
    budgetAED: 1800,
    details: 'Looking for municipality-approved HVAC technician team with camera inspection and antibacterial fogging treatment for 4 bedroom independent villa.',
    status: 'comparing' as const,
    createdAt: '2026-09-04T14:30:00Z',
    quotesCount: 3,
  },
  {
    id: 'req_3',
    userId: 'guest',
    userName: 'Elena Rostova',
    userPhone: '+971 52 444 8899',
    userEmail: 'elena.rost@example.com',
    title: 'Custom Pastel Balloon Garland & Themed Backdrop for 5th Birthday',
    category: 'Events & Party',
    city: 'Dubai' as const,
    district: 'Dubai Marina',
    neededDate: 'Next Sunday afternoon',
    budgetAED: 950,
    details: 'Under-the-sea pastel theme (lavender, mint, pearl white, soft coral) 3-meter balloon arch with personalized wooden cutout name board.',
    status: 'request_sent' as const,
    createdAt: '2026-09-05T08:20:00Z',
    quotesCount: 1,
  },
];

export const initialRequestQuotes = [
  {
    id: 'quote_1',
    requestId: 'req_1',
    businessId: 'biz_artisan_bakers',
    businessName: 'Artisan French Bakery & Catering UAE',
    businessRating: 4.9,
    businessPhone: '+971 4 332 8900',
    priceAED: 1050,
    availability: 'Confirmed Friday 7:00 AM delivery',
    minOrder: '200 pieces',
    deliveryTerms: 'Free refrigerated van delivery directly to Downtown venue',
    completionTime: 'Ready by 6:45 AM Friday',
    notes: 'Baked fresh at 4:30 AM with authentic Normandy butter. Includes 6 luxury eco-friendly wooden presentation trays.',
    createdAt: '2026-09-04T11:00:00Z',
    status: 'pending' as const,
  },
  {
    id: 'quote_2',
    requestId: 'req_1',
    businessId: 'biz_gourmet_wholesalers',
    businessName: 'Dubai Pastry Hub Wholesalers',
    businessRating: 4.7,
    businessPhone: '+971 4 228 1144',
    priceAED: 920,
    availability: 'Available on Friday morning',
    minOrder: '250 pieces',
    deliveryTerms: 'AED 50 delivery fee or free warehouse pickup in Al Quoz',
    completionTime: 'Delivery between 7:00 AM - 7:30 AM',
    notes: 'Standard catering boxes with grease-proof paper. High quality Belgian chocolate filling.',
    createdAt: '2026-09-04T12:45:00Z',
    status: 'pending' as const,
  },
  {
    id: 'quote_3',
    requestId: 'req_2',
    businessId: 'biz_pureair_uae',
    businessName: 'PureAir Technical Services Dubai',
    businessRating: 4.9,
    businessPhone: '+971 4 800 2472',
    priceAED: 1650,
    availability: 'Available Saturday 9:00 AM',
    minOrder: 'Single villa job',
    deliveryTerms: 'On-site service by 4 licensed technicians',
    completionTime: 'Approx 3.5 - 4 hours complete job',
    notes: 'Includes full video robotic camera before/after report, coil pressure washing, microbial disinfection fogging, and free 3-month guarantee.',
    createdAt: '2026-09-04T16:00:00Z',
    status: 'pending' as const,
  },
  {
    id: 'quote_4',
    requestId: 'req_3',
    businessId: 'biz_balloon_magic',
    businessName: 'Balloon Magic & Party Styling DXB',
    businessRating: 4.8,
    businessPhone: '+971 50 998 1234',
    priceAED: 890,
    availability: 'Sunday 1:00 PM setup',
    minOrder: 'AED 500 minimum',
    deliveryTerms: 'Free setup and dismantling within Dubai Marina',
    completionTime: '2 hours on-site installation before event',
    notes: 'Biodegradable latex balloons, double-stuffed pastel pigments for matte finish, customized laser-cut name topper included.',
    createdAt: '2026-09-05T10:00:00Z',
    status: 'pending' as const,
  },
];

export const initialFindMeProducts = [
  {
    id: 'prod_1',
    businessId: 'biz_artisan_bakers',
    businessName: 'Artisan French Bakery',
    title: 'Butter Croissant (Box of 12)',
    category: 'Food & Beverage',
    priceAED: 68,
    unit: 'box',
    inStock: true,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
    city: 'Dubai' as const,
    description: 'Crispy, flaky, golden traditional butter croissants baked daily.',
    tags: ['bakery', 'croissant', 'breakfast', 'pastry', 'french'],
  },
  {
    id: 'prod_2',
    businessId: 'biz_gourmet_wholesalers',
    businessName: 'Fresh Mart Hypermarket',
    title: 'Organic Fairtrade Colombian Coffee Beans (1kg)',
    category: 'Shopping',
    priceAED: 85,
    unit: 'kg',
    inStock: true,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=800',
    city: 'Dubai' as const,
    description: 'Whole bean medium dark roast with notes of chocolate and hazelnut.',
    tags: ['coffee', 'beans', 'supermarket', 'organic', 'beverage'],
  },
  {
    id: 'prod_3',
    businessId: 'biz_balloon_magic',
    businessName: 'Balloon Magic DXB',
    title: 'Organic Pastel Balloon Arch Kit (500 pcs)',
    category: 'Events & Party',
    priceAED: 240,
    unit: 'kit',
    inStock: true,
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&q=80&w=800',
    city: 'Dubai' as const,
    description: 'Complete DIY party garland kit with dual-action pump and framing tape.',
    tags: ['balloons', 'party', 'decoration', 'birthday', 'event'],
  },
  {
    id: 'prod_4',
    businessId: 'biz_wholesale_office',
    businessName: 'Emirates Paper & Packaging Wholesalers',
    title: 'Custom Printed Kraft Paper Takeaway Bags (Carton 500x)',
    category: 'Business & Wholesale',
    priceAED: 320,
    unit: 'carton',
    inStock: true,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800',
    city: 'Dubai' as const,
    description: 'Heavy duty twisted handle recycled kraft paper bags for shops and restaurants.',
    tags: ['packaging', 'bags', 'wholesale', 'paper', 'retail', 'restaurant'],
  },
];

export const initialFindMeServices = [
  {
    id: 'serv_1',
    businessId: 'biz_pureair_uae',
    businessName: 'PureAir Technical Services',
    title: 'Residential AC Cleaning & Gas Top-Up',
    category: 'Home & Maintenance',
    startingPriceAED: 180,
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=800',
    city: 'Dubai' as const,
    description: 'Full split and ducted AC sanitization, coil wash, and chemical antibacterial cleaning.',
    tags: ['ac repair', 'handyman', 'cleaning', 'maintenance', 'home'],
  },
  {
    id: 'serv_2',
    businessId: 'biz_autocare_dxb',
    businessName: 'Apex Auto Care & Diagnostics',
    title: 'Comprehensive Major Car Service & 40-Point Inspection',
    category: 'Automotive',
    startingPriceAED: 350,
    image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=80&w=800',
    city: 'Dubai' as const,
    description: 'Synthetic engine oil change, filter replacement, brake inspection, and computerized OBD diagnostics.',
    tags: ['car', 'mechanic', 'auto', 'oil change', 'automotive'],
  },
  {
    id: 'serv_3',
    businessId: 'biz_balloon_magic',
    businessName: 'Balloon Magic DXB',
    title: 'Full Event Decoration & Birthday Venue Styling',
    category: 'Events & Party',
    startingPriceAED: 650,
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800',
    city: 'Dubai' as const,
    description: 'Custom theme design, table centerpieces, photo-backdrop, and on-site event coordinator.',
    tags: ['event', 'party', 'birthday', 'catering', 'decor'],
  },
];

